source = "cyberFund"
dependencies = ["independent"]
system = "Stellar"

[descriptions]
headline = "A public infrastructure for money"
state = "Running"
tags = ["DAO"]
hashtag = "#stellar"
system_type = ""

[aliases]
coinmarketcap = "Stellar"
CurrencyName = "Stellar"

[ratings]
rating_cyber = 3.0

[consensus]
consensus_name = "Federated Consensus"
hashing = "Scrypt"
consensus_type = ""

[events]
announcement = "01/08/2014"
genesis = "01/08/2014"

[token]
token_name = ""
token_symbol = "STR"

[specs]
total_tokens = 100000000000.0
p2p = 18216.0
rpc = 18217.0
block_time = 30.0
block_reward = 100.0
halfing_cycle = 1051200.0
difficulty_cycle = "every block"
txs_confirm = 4.0
mint_confirm = 70.0

[[links]]
name = "stellar.org"
url = "https://www.stellar.org/"
icon = "website.png"
type = "site"
tags = ["Main"]

[[links]]
name = "Stellar GitHub"
url = "https://github.com/stellar/stellar-core"
icon = "github.png"
type = "github"
tags = ["Code"]

[[links]]
name = "Documentation"
url = "https://www.stellar.org/papers/stellar-consensus-protocol.pdf"
icon = "whitepaper.png"
type = "whitepaper"
tags = ["Science"]

[[links]]
name = "explorer"
url = "http://stellarchain.io/"
icon = "explorer.png"
type = "explorer"
tags = ["Main", "Analytics"]

[[links]]
name = "@stellarorg"
url = "https://twitter.com/stellarorg"
icon = "twitter.png"
type = "twitter"
tags = ["Main", "News"]

[[links]]
name = "Forum"
url = "https://stellartalk.org/"
icon = "forum.png"
type = "forum"
tags = ["News"]

[[links]]
name = "Blog"
url = "https://www.stellar.org/blog/"
icon = "blog.png"
type = "blog"
tags = ["News"]

[[links]]
name = "reddit"
url = "https://www.reddit.com/r/stellar"
icon = "reddit.png"
type = "reddit"
tags = ["News"]

[[links]]
name = "Announcement"
url = "https://bitcointalk.org/index.php?topic=720096.0"
type = "custom"
tags = ["publications"]

[[links]]
name = "Stellar API"
url = "https://www.stellar.org/api/"
icon = "github.png"
type = "github"
tags = ["Code"]

[[links]]
name = "Stellar Roadmap"
url = "https://trello.com/b/Clb1VMP5/platform-roadmap"
icon = "link.png"
type = "custom"
tags = ["Code"]

[[links]]
name = "Stellar Wallet"
url = "https://launch.stellar.org/"
type = "wallet"
icon = "wallet.png"
tags = ["Main","Apps","Wallet"]

[[links]]
name = "Markets CMC"
headline = "nein"
url = "http://coinmarketcap.com/currencies/stellar/#markets"
type = "custom"
icon = "link.png"
tags = ["Apps","Analytics"]

[[links]]
name = "Poloniex"
headline = "nein"
url = "https://www.poloniex.com"
type = "custom"
icon = "poloniex.png"
tags = ["Apps","Exchange"]

[[links]]
name = "BTC38"
headline = "Cryptocurrensy Exchange"
url = "http://www.btc38.com/trade_en.html"
type = "custom"
icon = "btc38.png"
tags = ["Apps","Exchange"]

[[links]]
name = "Kraken"
headline = "nein"
type = "custom"
icon = "kraken.png"
url = "https://www.kraken.com"
tags = ["Apps","Exchange"]

[[links]]
name = "Bittrex"
headline = "nein"
url = "https://bittrex.com"
type = "custom"
icon = "bittrex.png"
tags = ["Apps","Exchange"]

